"""Detail trade model

Revision ID: 488788c48c11
Revises: 66704804c9a3
Create Date: 2025-09-29 00:30:11.937718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488788c48c11'
down_revision: Union[str, None] = '66704804c9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('size', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('price_entry', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('date_entry', sa.Date(), nullable=True))
    op.add_column('trades', sa.Column('price_exit', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('date_exit', sa.Date(), nullable=True))
    op.add_column('trades', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('pnl_comm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'pnl_comm')
    op.drop_column('trades', 'pnl')
    op.drop_column('trades', 'date_exit')
    op.drop_column('trades', 'price_exit')
    op.drop_column('trades', 'date_entry')
    op.drop_column('trades', 'price_entry')
    op.drop_column('trades', 'size')
    # ### end Alembic commands ###
